---
# tasks file for ansible-role-apisix

# Triggers handlers from dependent roles
- name: Trigger role handlers
  meta: flush_handlers

- name: Setup APISIX
  ansible.builtin.include_tasks: apisix.yml

- name: Setup APISIX Dashboard
  ansible.builtin.include_tasks: apisix-dashboard.yml