# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "node01" do |node01|
    node01.vm.box = "generic/rocky8"
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.56.10"
    node01.vm.network "public_network", ip: "192.168.56.10"
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "generic/rocky8"
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.56.11"
    node02.vm.network "public_network", ip: "192.168.56.11"
    node02.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end

  config.vm.define "node03" do |node03|
    node03.vm.box = "generic/rocky8"
    node03.vm.hostname = "node03"
    node03.vm.network "private_network", ip: "192.168.56.12"
    node03.vm.network "public_network", ip: "192.168.56.12"
    node03.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
    end
  end
end