---
# handlers file for ansible-role-apisix
- name: Run APISIX Docker container
  community.docker.docker_container:
    name: apisix
    state: started
    image: apache/apisix:2.13.1-alpine
    network_mode: host
    restart: true
    volumes:
      - /var/log/apisix:/usr/local/apisix/logs
      - /etc/apisix/apisix.conf.yaml:/usr/local/apisix/conf/config.yaml
    restart_policy: unless-stopped

- name: Run APISIX dashboard Docker container
  community.docker.docker_container:
    name: apisix-dashboard
    state: started
    image: apache/apisix-dashboard:2.13-alpine
    network_mode: host
    restart: true 
    volumes:
      - /etc/apisix/apisix-dashboard.conf.yaml.j2:/usr/local/apisix-dashboard/conf/conf.yaml
    restart_policy: unless-stopped